version: "3.9"
services:
  fl-client:
    build: ./client
    ports:
      - "8002:8002"
    environment:
      - TZ=Asia/Seoul
    networks:
      - fedops
  client-manager:
    build: ./client_manager
    ports:
      - "8003:8003"
    environment:
      - TZ=Asia/Seoul
    networks:
      - fedops
networks:
  fedops:
    driver: bridge